# Generated by Django 4.1.2 on 2023-08-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anggota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("tgl_lahir", models.DateField()),
                ("pekerjaan", models.CharField(blank=True, max_length=100)),
                ("alamat", models.CharField(blank=True, max_length=100)),
                ("domisili", models.CharField(blank=True, max_length=100)),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keluarga", models.CharField(max_length=50)),
                ("tgl_pernikahan", models.DateField()),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "Keluarga",
            },
        ),
        migrations.CreateModel(
            name="Keuangan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uraian", models.TextField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("tanggal", models.DateField()),
                ("jumlah", models.FloatField(blank=True)),
                ("huria", models.FloatField(blank=True)),
                ("pusat", models.FloatField(blank=True)),
                ("pembangunan", models.FloatField(blank=True)),
                ("jenis", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="KeuanganPospel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uraian", models.TextField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("tanggal", models.DateField()),
                ("debit", models.FloatField(blank=True)),
                ("kredit", models.FloatField(blank=True)),
                ("jenis", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Posisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "posisi",
            },
        ),
        migrations.CreateModel(
            name="Pospel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "pospel",
            },
        ),
        migrations.CreateModel(
            name="Sektor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "sektor",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "posisi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.posisi",
                    ),
                ),
            ],
        ),
    ]
