# Generated by Django 4.1.2 on 2023-08-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anggota",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.staff"
            ),
        ),
        migrations.AddField(
            model_name="keluarga",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.staff"
            ),
        ),
        migrations.AddField(
            model_name="keuangan",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.staff"
            ),
        ),
        migrations.AddField(
            model_name="keuanganpospel",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.staff"
            ),
        ),
    ]
