# Generated by Django 4.1.2 on 2023-08-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_keluarga_created_keluarga_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keuangan",
            name="huria",
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="keuangan",
            name="jumlah",
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="keuangan",
            name="pembangunan",
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="keuangan",
            name="pusat",
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="keuanganpospel",
            name="debit",
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="keuanganpospel",
            name="kredit",
            field=models.BigIntegerField(blank=True),
        ),
    ]
