# Generated by Django 4.1.2 on 2023-08-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_category_keuangan_kategori"),
    ]

    operations = [
        migrations.CreateModel(
            name="TahunAnggaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name_plural": "TahunAnggaran",
            },
        ),
    ]
